### ISSUE TITLE
There is a space between the + and the number

### ISSUE THREAD

**Issue by chmike** [magicmonty/bash-git-prompt#152]
Why is there a space between the + and the number of modified files ?
This is visble in the screen capture in the README.md file. 
Other symbols don't have such space.

**Comment by magicmonty** [comment]
This is because of a quirk with terminal fonts. Under OSX the default terminal font is Monaco, and if there  is no space between the ✚ and the Number this would look like this:

![image](https://cloud.githubusercontent.com/assets/315639/9638107/e46a5b46-51a4-11e5-8e39-b6e49910d4ca.png)

I have currently no idea how to fix this generally. The best option is here to make a custom theme without the space.

**Comment by chmike** [comment]
I made my own custom theme with different characters so that I don't have space problems.
  GIT_PROMPT_BRANCH="${Green}"
  GIT_PROMPT_REMOTE=" "
  GIT_PROMPT_SYMBOLS_NO_REMOTE_TRACKING="⭐"

  GIT_PROMPT_SEPARATOR="|"
  GIT_PROMPT_CHANGED="${Cyan}❗"
  GIT_PROMPT_STAGED="${Yellow}▸"
  GIT_PROMPT_UNTRACKED="${Blue}…"
  GIT_PROMPT_CONFLICTS="${BoldRed}❓"
  GIT_PROMPT_STASHED="${Magenta}>"
  GIT_PROMPT_CLEAN="${Green}✔ "
  GIT_PROMPT_COMMAND_OK="${Green}✔"
  GIT_PROMPT_COMMAND_FAIL="${Red}✘"

**Comment by magicmonty** [comment]
Sweet, I just added it as a new Theme (named Chmike ;) )
