### ISSUE TITLE
Security issue with SSH key prompt

### ISSUE THREAD

**Issue by awstlaur** [magicmonty/bash-git-prompt#242]
I have git set up to use ssh with github.

When I `cd` into a repo, or sometimes when I enter a blank line in the terminal, I'm greeted with the prompt to enter the passphrase for my ssh key. However, instead hidden of input on the same line, as would be expected, I am prompted for cleartext input on the next line. But then this cleartext input is interpreted by bash, not by git.

When I run something like `git pull`, it prompts for my passphrase the secure/correct way.

```
✔ /home/awstlaur/repos/<project> [<branch>|✚ 1] 
12:19 $ Enter passphrase for key '/home/awstlaur/.ssh/<rsa key>': 
<my cleartext input>
bash: <my cleartext input>: command not found
✘-127 /home/awstlaur/repos/<project> [<branch>|✚ 1] 
12:19 $ git pull
Enter passphrase for key '/home/awstlaur/.ssh/<rsa key>': <hidden input>
X11 forwarding request failed on channel 0
Already up-to-date.
✔ /home/awstlaur/repos/<project> [<branch>|✚ 1]
12:19 $
```

**Comment by ogr3** [comment]
You should use a passphrase-free key or look into using ssh-agent if you want bash-git-prompt to fetch repo info in the background. The git status is spawned in a sub-shell in order to not lock up the prompt when querying the server.

https://en.wikipedia.org/wiki/Ssh-agent

Or you can turn off bash-git-prompt status querying in the background:

```
GIT_PROMPT_FETCH_REMOTE_STATUS=0
```

**Comment by awstlaur** [comment]
Thanks for the solutions!
