### ISSUE TITLE
Possibly unintended check mark in the prompt?

### ISSUE THREAD

**Issue by Arthur-W-White** [magicmonty/bash-git-prompt#318]
![screenshot from 2017-04-10 11-05-55](https://cloud.githubusercontent.com/assets/27197061/24851921/2275e2fa-1dde-11e7-98ec-fb5066af14cf.png)
There is a check mark in the beginning of the prompt line which looks like it might be out of place?

This is on a clean install of Ubuntu 16.4.

**Comment by ogr3** [comment]
It's an indicator of the exit state of the last command. If you don't want that, use a theme with `NoExitState` in the name.

Since you are using Ubuntu, it probably will look best if you use a theme with `Ubuntu` in it as well.

Just set

`GIT_PROMPT_THEME=Default_NoExitState_Ubuntu`

Before loading the prompt.
