### ISSUE TITLE
Allow bypassing checking remote status for https remotes

### ISSUE THREAD

**Issue by behrangs-sportsbet** [magicmonty/bash-git-prompt#354]
Some of my repos have `https` remotes. Every now and then, when I cd into these repos, I get prompted to enter my username/password:

<img width="295" alt="screen shot 2017-11-01 at 11 52 11 am" src="https://user-images.githubusercontent.com/32662701/32255409-d4f2a27e-befb-11e7-85ee-34b825d514f2.png">

Is there a way yo skip checking remote status for these `https` repos (something like `GIT_PROMPT_FETCH_REMOTE_STATUS=0`, but only for repos with `https` origins).

**Comment by jmohr00** [comment]
There doesn't appear to be a need for a separate option. If a password is needed, the fetch will fail regardless since stdin isn't a tty when it runs the fetch command. How about just suppressing the (useless) password prompt by temporarily setting GIT_TERMINAL_PROMPT to 0 for the fetch command?

**Comment by ogr3** [comment]
Is that really so?

I have entered the username and password when prompted, and it works, so I don't think you should suppress the prompting. Best choice is of course to setup ssh agent so that you key is not password prompted.

**Comment by jmohr00** [comment]
OK, sorry. I was only testing the script while logged into a machine remotely over SSH. If a GUI is not available `git fetch` will attempt to ask for credentials via stdin, which is not possible in this script because `async_run` detaches stdin. At that point it's just extra, confusing output. These are the prompts that are suppressed by setting `GIT_TERMINAL_PROMPT=0`. On the other hand, testing it locally on my Windows machine now I see that there are pop-up prompts in a separate GUI window. These pop-ups are NOT suppressed by setting `GIT_TERMINAL_PROMPT=0`.

So this change is probably a good idea in addition to an option to disable fetching on HTTPS remotes. I'd be happy to work on adding the option as well. Thanks for your patience
