### ISSUE TITLE
Newline before start of bash-git-prompt

### ISSUE THREAD

**Issue by pbnj** [magicmonty/bash-git-prompt#446]
First, thank you for this project.

I am trying to insert a newline before bash-git-prompt with `GIT_PROMPT_START="\n"` (as discussed in #76 ).
But this seems to overwrite the last status indicator and the current working directory.

![Screen Shot 2019-08-03 at 10 23 33 PM](https://user-images.githubusercontent.com/6811830/62419776-637e6980-b63d-11e9-9c17-18795c86de45.png)

I also tried adding the newline before sourcing `gitprompt.sh`.

After a quick inspection of `gitprompt.sh`, I found that `GIT_PROMPT_START` overwrites `PROMPT_START`, which I was not expecting.

Is there a way to simply add a newline before bash-git-prompt while maintaining everything else as-is?

**Comment by petermbenjamin** [comment]
In the meantime, my workaround is to use `Minimal` theme with `GIT_PROMPT_START="\n"` (and `GIT_PROMPT_END="\n$ "` instead of the right arrow prompt symbol), which produces the desired outcome for me

![Screen Shot 2019-08-03 at 11 01 23 PM](https://user-images.githubusercontent.com/6811830/62420161-aabb2900-b642-11e9-96fd-9f65365945c5.png)

But, it would be nice to know if this is possible with the default theme.

**Comment by alexandrul** [comment]
The Solarized theme works on my PC (so far) with the following changes:

```
@@ -338,7 +338,7 @@ function setGitPrompt() {
   git_prompt_config

   if [[ ! -e "${repo}" ]] || [[ "${GIT_PROMPT_DISABLE-}" = 1 ]]; then
-    PS1="${EMPTY_PROMPT}"
+    PS1="\n${EMPTY_PROMPT}"
     return
   fi

@@ -596,7 +596,7 @@ function updatePrompt() {
     NEW_PROMPT="${EMPTY_PROMPT}"
   fi

-  PS1="${NEW_PROMPT//_LAST_COMMAND_INDICATOR_/${LAST_COMMAND_INDICATOR}${ResetColor}}"
+  PS1="\n${NEW_PROMPT//_LAST_COMMAND_INDICATOR_/${LAST_COMMAND_INDICATOR}${ResetColor}}"
   command rm "${GIT_INDEX_PRIVATE}" 2>/dev/null
 }
```
