### ISSUE TITLE
Solarized_UserHost showing up as 'root@localhost #️ {ResetColor}' and keeping red color

### ISSUE THREAD

**Issue by kisp** [magicmonty/bash-git-prompt#526]
When I ssh into my Arch Linux box the prompt is shown as

```
✔ ~
root@localhost #️ {ResetColor}
```

and the color for typing commands is red.

Can you help me tracking down why this happens? :)

**Comment by kisp** [comment]
cc @rkitover @guenhter

I did a git bisect and https://github.com/magicmonty/bash-git-prompt/commit/0eb0947955ccf2855dcef88ad48aaef1fbb5c188 was identified as the problematic commit.

Indeed, when I run `git revert 0eb0947955ccf2855dcef88ad48aaef1fbb5c188`, the problem goes away and my prompt is shown as

```
✔  ~
root@localhost  #️
```

**Comment by kisp** [comment]
Oh, I see... I think the `GIT_PROMPT_END_ROOT` version misses a `$`.

`#️ {ResetColor}` should be `#️ ${ResetColor}`

Do you want me to provide a PR? :)

**Comment by rkitover** [comment]
Hi @kisp, sorry about that.

By the way, I am working on my own prompt, which is similar to this theme:

https://github.com/rkitover/sh-prompt-simple

**Comment by rakotomandimby** [comment]
Hello,

In the issue https://github.com/magicmonty/bash-git-prompt/issues/517, the maintainer has announced his retirement from this project.

I forked it on https://github.com/rakotomandimby/bash-git-prompt, and if this issue is still relevant, I kindly ask you to re-create it over there, and provide the pull request over there.

Thank you
